version: '3.8'

services:
  mysql_test:
    image: mysql:5.7
    container_name: 'banksystem_mysql_test'
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    expose:
      - '3306'
    ports:
      - '3306:3306'
    volumes:
      - ~/volumes/mysql:/var/lib/mysql_test
    networks:
      - banksystem_test

  api_test:
    image: node:12
    container_name: 'banksystem_api_test'
    command: yarn run test:api
    ports:
      - '3000:3000'
    volumes:
      - .:/srv/api:rw
    working_dir: /srv/api
    links:
      - mysql_test
    depends_on:
      - mysql_test
    networks:
      - banksystem_test

networks:
  banksystem_test:
